---
- name: Setup application
  hosts: localhost
  vars:
    couchdb_container: vue-couchdb
    pos_container: nginx_pos

  tasks:

    - name: Include variables
      include_vars:
        file: variables.yaml
      
      tags:
        - import_vars

    - name: Start couchdb container
      containers.podman.podman_container:
        name: "{{ couchdb_container }}"
        image: localhost/couchdb
        state: started
        restart: yes
        ports:
          - "5984:5984"
        env:
          COUCHDB_USER="{{ couchdb_admin_user }}"
          COUCHDB_PASSWORD="{{ couchdb_admin_password }}"

      tags:
        - start_couch
        - start_all

    - name: Stop couchdb container
      containers.podman.podman_container:
        name: "{{ couchdb_container }}"
        state: stopped
      
      tags:
        - stop_couch
        - stop_all
        - clean
    
    - name: Remove couchdb container
      containers.podman.podman_container:
        name: "{{ couchdb_container }}"
        state: absent
      
      tags:
        - remove_couch
        - clean
    
    - name: Stop frontend container
      containers.podman.podman_container:
        name: "{{ pos_container }}"
        state: stopped
      
      tags:
        - stop_pos
        - rebuild_pos
        - stop_all
        - clean

    - name: Remove frontend container
      containers.podman.podman_container:
        name: "{{ pos_container }}"
        state: absent
      
      tags:
        - remove_pos 
        - rebuild_pos
        - restart_pos
        - clean

    - name: Remove web app container
      podman_image:
        name: localhost/nginx_pos
        state: absent

      tags:
        - remove_pos_image
        - clean
        - rebuild_pos

    - name: Build web app container
      podman_image:
        name: nginx_pos
        path: app/
        build:
          format: docker
      
      tags:
        - build_pos_image
        - rebuild_pos

    - name: Create/start frontend container
      containers.podman.podman_container:
        name: "{{ pos_container }}"
        image: localhost/nginx_pos
        state: started
        restart: yes
        ports:
          - "8443:8443"
          - "8080:8080"
        env:
          COUCHDB_HOST="{{ host_ip }}"

      tags:
        - rebuild_pos
        - restart_pos
        - start_pos
        - start_all

    - name: Remove couchdb container
      podman_image:
        name: localhost/couchdb
        state: absent

      tags:
        - remove_couch_image
        - clean
    
    - name: Build couchdb container
      podman_image:
        name: couchdb
        path: couchdb_container
        build:
          format: docker
      
      tags:
        - build_couch_image