FROM registry.access.redhat.com/ubi8/ubi-minimal

LABEL name="pos-app" \
      vendor="opensource" \
      version="1" \
      release="1" \
      summary="Nginx container to host vuepos collections" \
      description="Nginx container to host vuepos collections"

COPY nginx/nginx.repo  /etc/yum.repos.d/nginx.repo

RUN microdnf install nginx findutils \
    && mkdir /var/cache/nginx \
    && chown -R nginx:0 /var/log/nginx/ /var/cache/nginx /usr/share/nginx \
    && chmod -R g=u /var/log/nginx/ /var/cache/nginx /usr/share/nginx \
    && mkdir /licenses \
    && cp /usr/share/doc/nginx*/* /licenses

COPY nginx/nginx.conf  /etc/nginx/nginx.conf
COPY nginx/nginx-ssl.conf  /etc/nginx/nginx-ssl.conf
COPY nginx/startup.sh  /opt/startup.sh
COPY images /opt/www/public/images
COPY src /opt/www/public/src
COPY favicon.ico /opt/www/public
COPY index.html /opt/www/public
COPY manifest.json /opt/www/public
COPY offline.html /opt/www/public
COPY sw.js /opt/www/public

RUN touch /var/run/nginx.pid && \
  chown -R 1001:0 /var/run/nginx.pid /var/cache/nginx /opt/www/public /etc/nginx /run && \
  chmod -R g=u /opt/www/public /var/cache/nginx /etc/nginx /var/run/nginx.pid /run

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT ["/opt/startup.sh"]